---
name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install piper-phonemize
        run: |
          pip install ".[dev]"

      - name: Run tests
        run: python -m pytest tests/test_espeak_phonemizer.py tests/test_tashkeel.py -v
